config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {

    registrations: 'users/registrations',

    confirmations: 'users/confirmations',

    sessions: 'users/sessions',

    passwords: 'users/passwords'

  }

  namespace :admin do
    devise_scope :user do
      get '/register', to: 'registrations#new'
      post '/register', to: 'registrations#create'
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
    root to: 'dashboard#index'
  end

  resources :attendances, path: 'users/:user_id/attendances', except: %i[show destroy]
  resource :user_config, path: 'users/:user_id/config', except: %i[index new show destroy], controller: "users_config"

  root 'home#index'

  get '/users/:id/exportCsv', to: 'export_csv#export_csv'
  get '/users/:id/exportXlsx', to: 'export_xlsx#export_xlsx'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboard_controller.rb
module Admin
  # DashboardController
  class DashboardController < ApplicationController
    def index
      authorize :dashboard, :view?
      render 'admins/dashboard/index'
    end
  end
end

app/views/admins/dashboard/index.html.erb
<section class="section">
  <div class="columns">
    <div class="column">
      <%= link_to new_user_registration_path do %>
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="/assets/200x200.png" alt="Placeholder image" height="200" width="300">
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4">ユーザ追加画面</p>
              </div>
            </div>
            <div class="content">
              <p>新規ユーザーをチームに登録することができます。</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="column">
      <%= link_to user_session_path do %>
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="/assets/200x200.png" alt="Placeholder image" height="200" width="300">
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4">ユーザ情報画面</p>
              </div>
            </div>
            <div class="content">
              <p>チーム内の個別ユーザーの情報を参照・編集することができます。</p>
            </div>
          </div>
      <% end %>
      </div>
    </div>
    <div class="column">
      <%= link_to admin_register_path do %>
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="/assets/200x200.png" alt="Placeholder image" height="200" width="300">
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4">勤怠の承認画面</p>
              </div>
            </div>
            <div class="content">
              <p>チーム内のユーザーの承認依頼を一覧表示で見ることができます。</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="column">
      <%= link_to admin_login_path do %>

        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="/assets/200x200.png" alt="Placeholder image" height="200" width="300">
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4">ユーザ個別の設定画面</p>
              </div>
            </div>
            <div class="content">
              チーム内ユーザーの勤務時間の個別の設定をすることができます
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  </div>
</section>