config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {

    registrations: 'users/registrations',

    confirmations: 'users/confirmations',

    sessions: 'users/sessions',

    passwords: 'users/passwords'

  }

  namespace :admin do
    devise_scope :user do
      get '/register', to: 'registrations#new'
      post '/register', to: 'registrations#create'
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end
    root to: 'dashboard#index'
  end

  resources :attendances, path: 'users/:user_id/attendances', except: %i[show destroy]
  resource :user_config, path: 'users/:user_id/config', except: %i[index new show destroy], controller: "users_config"

  root 'home#index'

  get '/users/:id/exportCsv', to: 'export_csv#export_csv'
  get '/users/:id/exportXlsx', to: 'export_xlsx#export_xlsx'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
# At
class Attendance < ApplicationRecord
  belongs_to :user
end

app/controllers/attendances_controller.rb
# AttendancesControllerF
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @attendances = Attendance.where(user_id: @user.id)
    paramdate = params[:date]

    @today = paramdate ? paramdate.to_date : Date.current
    dead_line = Date.new(2022, 6, 22)

    @dateindex = (@today.beginning_of_month - dead_line.beginning_of_month + 1).to_i

    @cuurentdateindex = (Date.current.beginning_of_month - dead_line.beginning_of_month + 1).to_i

    @isviewrightarrow = @today.month - Date.current.month <= 1 || @today.year < Date.current.year

    @daylist = @today.all_month.to_a
  end

  def new
    @attendances = Attendance.new
  end

  def edit
    @attendances = Attendance.find(params[:id])
  end

  def create
    @attendance = current_user.attendance.build(user_params)
    if @attendance.save

      redirect_to action: :index

    else

      render 'index'

    end
  end

  def update
    @attendances = Attendance.find(params[:id])

    @attendances.assign_attributes(update_parameters)

    if @attendances.save

      redirect_to action: :index, status: :see_other

    else

      render 'index'

    end
  end

  def user_params
    params.require(:attendance).permit(
      :id, :start_time, :end_time, :attendances_time, :date, :end_default_time,
      :rest_time, :actual_time, :overtime, :attendances_flag
    )
  end

  def update_parameters
    params.require(:attendance).permit(:start_time, :rest_time, :end_time, :actual_time)
  end
end

app/views/attendances/edit.html.erb
<section>
  <%= form_with class: "box", model: @attendances, url: attendance_path, local: true do |form| %>
    <div class="field">
      <label class="label">勤務時間</label>
      <div class="field has-addons">
        <div class="control">
          <a class="button is-static">開始時間</a>
        </div>
        <div class="control">
          <%= form.text_field :start_time %>
        </div>
        <div class="control">
          <a class="button is-static">終了時間</a>
        </div>
        <div class="control">
          <%= form.text_field :end_time, value: @attendances ? @attendances.end_time&.strftime("%H:%M") : "" %>
        </div>
      </div>
    </div>
    <div class="field">
      <label class="label">休憩時間</label>
      <div class="field has-addons">
        <div class="control">
          <a class="button is-static">休憩時間</a>
        </div>
        <div class="control">
          <%= form.text_field :rest_time, value: @attendances ? @attendances
            .rest_time&.strftime("%H:%M") : "" %>
        </div>
      </div>
      <%= form.submit %>
    </div>
    </div>
  <% end %>
</section>

app/views/attendances/index.html.erb
<section class="section">
  <div>
    <h2 class="h2">勤怠テーブル</h2>
  </div>
  <span style="display: none" id="dateId">
    <%= @dateindex + 1 %>
  </span>
  <span style="display: none" id="currentDateId">
    <%= @cuurentdateindex + 1 %>
  </span>
  <span id="userId" style="display: none">
    <%= @user.id %>
  </span>
  <div class="columns" style="align-items:normal">
    <div class="column is-one-third">
      <div class="card">
        <div class="card-image">
          <figure class="image is-4by3">
            <img src="/assets/200x200.png" alt="Placeholder image" height="200" width="300">
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">田中隆</p>
            </div>
          </div>
          <div class="content">
            <span id="user_email">shigoto922@gmail.com</span>
            <br>
            <span id="sex">男性</span>
            <div class="mt-3 ui divided selection list">
              <div class="mb-2 is-flex-desktop">
                <div class="p-1 has-background-info has-text-white">開始時間</div>
                <span class="ml-4" id="ordinaly_start_time">09:00</span>
              </div>
              <hr/>
              <div class="mb-2 is-flex-desktop">
                <div class="p-1 has-background-info has-text-white">終了時間</div>
                <span class="ml-4" id="ordinaly_end_time">17:30</span>
              </div>
              <hr/>
              <div class="mb-2 is-flex-desktop">
                <div class="p-1 has-background-info has-text-white">休憩時間</div>
                <span class="ml-4" id="ordinaly_lunch_time">01:00</span>
              </div>
              <hr/>
              <div class="mb-2 is-flex-desktop">
                <div class="p-1 has-background-info has-text-white">月の労働時間</div>
                <span class="ml-4" id="month_preset_time">150時間</span>
              </div>
              <hr/>
              <div class="mb-2 is-flex-desktop">
                <div class="p-1 has-background-info has-text-white">月給</div>
                <span class="ml-4" id="salary_setting">200000</span>円
              </div>
              <hr/>
            </div>
          </div>
        </div>
        <footer class="card-footer">
          <%= link_to "個人設定を変更する", edit_user_config_path, class: 'mx-5 mb-2 card-footer-item button is-info' %>
        </footer>
      </div>
    </div>
    <div class="column">
      <div class="block" style="width:100%">
        <span id="left-icon-arrow" class="icon">
          <i class="fas fa-arrow-left is-size-3"></i>
        </span>
        <span id="today" class="is-size-3"><%= @today.strftime("%Y/%m") %></span>
        <% if @isviewrightarrow %>
        <span id="right-icon-arrow" class="icon">
          <i class="fas fa-arrow-right is-size-3"></i>
        </span>
        <% end %>
        <button class="button is-link ml-5" id="startTime">出勤</button>
        <button class="button is-link" id="endTime">退勤</button>
        <button class="button is-primary ml-5" id="csvExport">csv出力</button>
        <button class="button is-primary" id="xlsxExport">excell出力</button>
      </div>
      <div class="block">
        <table class="table table-striped" style="width:100%"
        >
          <thead>
          <tr>
            <th>作業月</th>
            <th>所定時間</th>
            <th>稼働時間</th>
            <th>時間外</th>
            <th>稼働日数</th>
            <th>給与</th>
            <th>月の承認</th>
          </tr>
          </thead>
          <tbody>
          <tr></tr>
          </tbody>
        </table>
      </div>
      <div class="block">
        <table class="table" style="width:100%"
        >
          <thead>
          <tr>
            <th>編集</th>
            <th>区分</th>
            <th>日付</th>
            <th>開始</th>
            <th>所定終了</th>
            <th>終了</th>
            <th>休憩</th>
            <th>実働</th>
            <th>時間外</th>
            <th>承認</th>
            <th>日報</th>
          </tr>
          </thead>
          <tbody>
          <p>

          </p>
          <% @daylist.each.with_index(1) do |day, index| %>
            <% attendance = @attendances.detect { |attendance| attendance.id == @dateindex + index } %>
            <tr>
              <td class="id" style="display:none">
                <%= @dateindex + index %>
              </td>
              <td>
                <% if attendance %>
                  <%= link_to "編集", edit_attendance_path(id: @dateindex + index), class: "button is-primary" %>
                <% else %>
                  <%= link_to "作成", new_attendance_path(id: @dateindex + index), class: "button is-primary" %>
                <% end %>
              </td>
              <td>
                出勤
              </td>
              <td>
                <%= !attendance || !attendance.date ? day : attendance.date %>
              </td>
              <td class="start-time">
                <%= attendance ? attendance.start_time&.strftime("%H:%M") : "" %>
              </td>
              <td>
                <%= attendance ? attendance.end_default_time&.strftime("%H:%M") : "" %>
              </td>
              <td>
                <%= attendance ? attendance.end_time&.strftime("%H:%M") : "" %>
              </td>
              <td>
                <%= attendance ? attendance.rest_time&.strftime("%H:%M") : "" %>
              </td>
              <td>
                <%= attendance ? attendance.actual_time&.strftime("%H:%M") : "" %>
              </td>
              <td>
                <%= attendance ? attendance.rest_time&.strftime("%H:%M") : "" %>
              </td>
              <td>
                <button class="button is-primary">承認依頼</button>
              </td>
              <td>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.min.js" %>
<%= javascript_include_tag "abc.js" %>

app/views/attendances/new.html.erb
<section>
  <%= form_with class: "box", model: @attendances, url: @attendances, local: true do |form| %>
    <div class="field">
      <label class="label">勤務時間</label>
      <%= form.hidden_field :id, value: params[:id] %>
      <%= form.hidden_field :id, value: params[:id] %>
      <%= form.hidden_field :id, value: params[:id] %>
      <div class="field has-addons">
        <div class="control">
          <a class="button is-static">開始時間</a>
        </div>
        <div class="control">
          <%= form.text_field :start_time %>
        </div>
        <div class="control">
          <a class="button is-static">終了時間</a>
        </div>
        <div class="control">
          <%= form.text_field :end_time, value: @attendances ? @attendances.end_time&.strftime("%H:%M") : "" %>
        </div>
      </div>
    </div>
    <div class="field">
      <label class="label">休憩時間</label>
      <div class="field has-addons">
        <div class="control">
          <a class="button is-static">休憩時間</a>
        </div>
        <div class="control">
          <%= form.text_field :rest_time, value: @attendances ? @attendances
            .rest_time&.strftime("%H:%M") : "" %>
        </div>
      </div>
      <%= form.submit %>
    </div>
    </div>
  <% end %>
</section>